### ISSUE TITLE
NotificationsExtensions reference missing

### ISSUE THREAD

**Issue by Adrianotiger** [anbare/NotificationsExtensions#25] opened 2016-06-20 14:33 UTC
I have a problem with the latest version (14332.0.1).
If I add the NotificationsExtensions.Win10, I can compile it and it works. Once I close and open the project again, the solution want to load NotificationsExtensions and it can't find it.

If I install the 14332.0.0 version, it works without any errors.

I need to use
`using NotificationsExtensions;
`
`using NotificationsExtensions.Tiles;
`
if I want to use AdaptiveText.

**Comment by andrewleader** [comment] 2016-06-20 15:58
Hey!

What type of project are you adding the NuGet package into? Is it a UWP C# project? A WinRT C# project? A portable class library (if so, what are the targets of the library)?

I'll try closing and opening projects and see if I can repro anything, but if you can let me know what type of project you are using, that'll help!

**Comment by andrewleader** [comment] 2016-06-20 16:07
When adding the NuGet package to a UWP project, I'm seeing a build warning about not being able to resolve references... but I'm not seeing any errors. And the app still builds and runs correctly (generating notifications works).

This warning is definitely a result of how I had to change the NuGet package to support both JS and C++ UWP projects...

Let me know what type of project you are using.

**Comment by Adrianotiger** [comment] 2016-06-20 16:10
Hi. It is a C# UWP app. Once uploaded to the store, the Tile didnt updated un the phone and on the pc. So I was thinking it was related to this warning. But maybe there was an error on my code too...

**Comment by andrewleader** [comment] 2016-06-20 16:16
Was your app published with version 14332.0.0 of Extensions and working fine? If so, it's definitely the latest version that's probably causing your tile not to update!

You might want to revert back to 14332.0.0 while I figure out what's broken.

**Comment by Adrianotiger** [comment] 2016-06-20 18:24
No no, I didn't used version 0.0 before. My Tile didnt updated with version 0.1 and was thinking it was the extension causing it. Then I made some changes and used the version 0.0 and I didnt got any warnings and it works now. I will try to use again the version 0.1. Maybe it works but I was afraid for the warning message (reference not found)

**Comment by Adrianotiger** [comment] 2016-06-21 12:39
Hi Andrew,
sorry for the mistake. I compiled it and uploaded to the store with the last version and it works. The Tile didn't updated because I wrote a wrong path to an image. But even if I get this message:

> Failed to resolve all project references for 'xxx'. The package restore result for 'xxx.csproj' may be incomplete.

it works. Sorry!

**Comment by andrewleader** [comment] 2016-06-21 16:36
That's great, thanks!! I'll leave this issue open until I fix the warning, since ideally there shouldn't be any warnings.

Although there might not be any way for me to fix the warning AND support JavaScript/C++ UWP apps with the NuGet package, so the warning might have to stay. I'll play around with the NuGet package some more, and see if I can figure anything out.

**Comment by shahthepro** [comment] 2016-06-22 07:55
I am also getting the same warning in a C# UWP app. Whenever I install "NotificationsExtensions.Win10" from NuGet, A reference to "NotificationsExtensions" is also added to the project. 

![Have a look at this picture](https://cloud.githubusercontent.com/assets/10547529/16258722/bd353aae-387c-11e6-836a-ff12bd05b10f.png)

If I remove that reference, The warning disappears. But, the reference reappears if I close and open the solution.

**Comment by CordoWEB** [comment] 2016-06-24 12:35
I have the same issue on UWP project :(

**Comment by andrewleader** [comment] 2016-06-27 17:23
Are you folks still able to build and deploy your app, despite the warning? If this is a blocking issue for your app, please let me know.

**Comment by CordoWEB** [comment] 2016-06-27 19:06
It's not a blocking issue :)

I can generate my project in debug or release for the store but each time i restart VS2015 a new "NotificationsExtensions" appear in "Refrences". The "NotificationsExtensions.Win10" is already OK :)

It's exactly like shahthepro's screenshot.

**Comment by shahthepro** [comment] 2016-06-28 01:44
@anbare There is no problem in building or running the app. Even the notifications work as expected. Only that reference is added automatically causing a warning.

**Comment by andrewleader** [comment] 2016-07-01 16:50
I figured out how to fix this warning, I might submit an updated NuGet package soon! It's just a change to the NuGet package. It's tricky supporting JavaScript and C++ UWP apps in addition to C# and portable class libraries... but I think I've finally solved it without the warning in the C# project.

**Comment by andrewleader** [comment] 2016-07-05 21:38
Submitted updated NuGet packages fixing this! Latest version is here: https://www.nuget.org/packages/NotificationsExtensions.Win10/14332.0.2

Support for JavaScript UWP apps had to be broken out into a separate NuGet package (NotificationsExtensions.Win10.JavaScript). Everything should work in C# flawlessly now :)

**NOTE: After upgrading to the latest NuGet package, you will have to close and re-open your solution.** Otherwise you'll get build errors caused by the invalid reference from the previous version that's still lingering around.

Thanks everyone for pointing out this build warning! I wouldn't have caught it till later, it was odd in nature how it only appeared after closing and re-opening the solution!

**Closed as completed by andrewleader** 2016-07-05 21:38 UTC

**Comment by CordoWEB** [comment] 2016-07-05 22:21
Thanks a lot :)
Is it necessary to republish on the store app published with "buggy version" ?

**Comment by andrewleader** [comment] 2016-07-05 22:24
Nah you should be fine leaving your current app in the Store, I wouldn't submit an update to your app just for this. I would wait till you have some other changes you want to make. I don't believe the missing reference warning would have any performance impacts, since I would assume it is handled at compile-time, not runtime (but I'm no expert on that).
